spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true;databaseName=jwt_security
    username: sa
    password: VeryStr0ngP@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql:
    database: sql_server

jwt:
  secretKey: "884E635266556A586E3272357538782F413F4434572B4B6250645367566B5320"




